import './globals.css'
import type { Metadata } from 'next'
import { Oswald } from "next/font/google";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const oswald = Oswald({
  weight:'variable',
  variable:'--font-oswald',
  display:"swap",
  style:['normal'],
  subsets:['latin'],
  fallback:['system-ui']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
